[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pixeldriller"
version = "0.2.0"
dependencies = [
    "pystac-client>=0.4.0",
    "numpy"
]

[project.optional-dependencies]
docs = ["docutils<0.19", "sphinx<6", "numpydoc", "pydata-sphinx-theme"]
